import type { Metadata } from "next";
import "../globals.css";
import { Rubik } from 'next/font/google'
import { NavbarProvider } from "@/providers/NavProvider";
import NavbarToggle from "@/components/layout/nav/NavButton";
import NavBar from "@/components/layout/nav/Nav";
import AuthGuardProvider from "@/providers/AuthGuardProvider";


const rubik = Rubik({
  subsets: ['latin'],
  variable: '--font-rubik',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <AuthGuardProvider>
        <NavbarProvider>
          <NavbarToggle />
          <NavBar />
          {children}
        </NavbarProvider>
      </AuthGuardProvider>
    </div>

  );
}
